# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51bfbd9ceb879d50cef5f45f453ae1fe28b8c25a0c259e12bef5821003b1aee72e69088b5b0aa9dce82a705dcf76576a3f628f7b00aa372bb29e877889a3a17a

test:
  secret_key_base: 0e7cb327eac5920325f831644fb7fe6e4d0b954666de43727c90c55494f7f741736536d5d8b880022f56b8abdbd3b3a49bd8c0e899739f2a6899c26e08a50cda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
